/* IntelliTC Solutions — Mind Map Data: solar-roi */
window.MINDMAP_DATA = {
  title: "Solar ROI Calculator",
  tree: {
    name: "Solar ROI Analysis",
    children: [
      {
        name: "System Cost",
        children: [
          { name: "System Size (kW)", desc: "The power capacity of the solar panel installation in kilowatts." },
          { name: "Cost per Watt Installed ($/W)", desc: "The installation cost of the solar system divided by its capacity in watts." },
          { name: "Gross System Cost", desc: "System Cost before any deductions or expenses." },
          { name: "Federal ITC (30% Tax Credit)", desc: "Federal ITC — 30% Tax Credit." },
          { name: "State / Local Incentives", desc: "Additional rebates or tax credits offered by state or local governments for solar." },
          { name: "Net Cost After Incentives", desc: "Cost After Incentives remaining after all deductions and subtractions." }
        ]
      },
      {
        name: "Energy Savings",
        children: [
          { name: "Annual Energy Production (kWh)", desc: "The amount of electricity generated by the solar system." },
          { name: "Current Electricity Rate ($/kWh)", desc: "The price per kilowatt-hour currently charged by the utility company." },
          { name: "Annual Energy Bill Savings", desc: "Energy Bill Savings calculated on a annual basis." },
          { name: "Utility Rate Escalation (3-4%/yr)", desc: "Essential services including electricity, water, gas, and sewer." },
          { name: "Cumulative Savings Over 25 Years", desc: "The running total of savings over 25 years accumulated over time." }
        ]
      },
      {
        name: "Tax Credits & Incentives",
        children: [
          { name: "Federal Investment Tax Credit (ITC)", desc: "A dollar-for-dollar reduction in taxes owed, more valuable than a deduction." },
          { name: "SREC (Solar Renewable Energy Credits)", desc: "A federal tax credit equal to 30% of the solar system\'s cost." },
          { name: "State Income Tax Credit", desc: "Federal and/or state tax owed on rental income or investment gains." },
          { name: "Property Tax Exemption", desc: "An amount or type of income excluded from taxation under specific IRS rules." },
          { name: "MACRS Depreciation (Commercial)", desc: "The annual tax deduction for the wear and aging of the property\'s improvements." }
        ]
      },
      {
        name: "Payback Period",
        children: [
          { name: "Simple Payback = Net Cost / Annual Savings", desc: "Formula: Simple Payback = Net Cost / Annual Savings." },
          { name: "Payback Period (Years)", desc: "The number of years for energy savings to equal the system's installation cost." },
          { name: "Discounted Payback Period", desc: "The payback period adjusted for the time value of money." },
          { name: "Break-Even Year", desc: "The year when buying becomes financially advantageous compared to renting." }
        ]
      },
      {
        name: "Net Metering",
        children: [
          { name: "Excess Energy Exported to Grid", desc: "Surplus electricity produced by the solar system and sent back to the utility grid." },
          { name: "Net Metering Credit Rate", desc: "Metering Credit Rate remaining after all deductions and subtractions." },
          { name: "Annual Net Metering Credit Value", desc: "Net Metering Credit Value calculated on a annual basis." },
          { name: "True-Up Bill Calculation", desc: "The annual reconciliation of energy credits and charges under net metering." }
        ]
      },
      {
        name: "25-Year Return",
        children: [
          { name: "Total Lifetime Savings", desc: "The sum of all lifetime savings components." },
          { name: "System Degradation Rate (0.5%/yr)", desc: "System Degradation Rate — 0.5%/yr." },
          { name: "ROI (%)", desc: "Net profit divided by total investment, expressed as a percentage." },
          { name: "IRR of Solar Investment", desc: "The annualized return rate that makes the net present value of all cash flows equal to zero." },
          { name: "Increase in Property Value", desc: "The added property value attributable to the solar installation." }
        ]
      }
    ]
  }
};

// 23. Sources & Uses of Funds;
