/* IntelliTC Solutions — Mind Map Data: strategic-market-valuation */
window.MINDMAP_DATA = {
  title: "Strategic Market Valuation",
  tree: {
    name: "Market Valuation",
    children: [
      {
        name: "Income Approach",
        children: [
          { name: "Net Operating Income (NOI)", desc: "Gross income minus all operating expenses, before mortgage payments. The key measure of property profitability." },
          { name: "Direct Capitalization (NOI / Cap Rate)", desc: "Net Operating Income divided by property value, expressing the property\'s yield." },
          { name: "Market Cap Rate Selection", desc: "The prevailing cap rate for comparable properties in the local market." },
          { name: "Discounted Cash Flow (DCF)", desc: "The net income generated by the property after expenses and debt service." },
          { name: "Terminal Value (Exit Cap Rate)", desc: "The projected capitalization rate at the time of future sale, used to estimate exit value." },
          { name: "Income Approach Value", desc: "Property value estimated by capitalizing the net operating income using a market cap rate." }
        ]
      },
      {
        name: "Sales Comparison Approach",
        children: [
          { name: "Comparable Sales Selection", desc: "The criteria used to identify appropriate comparable properties." },
          { name: "Adjustment Grid", desc: "A table comparing the subject property to each comparable sale with value adjustments." },
          { name: "Price per SF Comparison", desc: "Comparing property values on a per-square-foot basis." },
          { name: "Price per Unit Comparison", desc: "The metric expressed per individual rental unit for standardized comparison." },
          { name: "GRM Comparison", desc: "Property price divided by gross annual rent — a quick valuation benchmark." },
          { name: "Adjusted Comparable Value", desc: "Value modifications applied to comparable properties to account for differences." }
        ]
      },
      {
        name: "Cost Approach",
        children: [
          { name: "Land Value (Separate)", desc: "The market value of the land excluding any structures." },
          { name: "Replacement Cost New (RCN)", desc: "The estimated cost to build an equivalent new structure from scratch." },
          { name: "Physical Depreciation", desc: "The annual tax deduction for the wear and aging of the property\'s improvements." },
          { name: "Functional Obsolescence", desc: "Value loss due to outdated design, layout, or features." },
          { name: "External Obsolescence", desc: "Value loss caused by factors outside the property, such as environmental or economic conditions." },
          { name: "Depreciated Improvement Value", desc: "The annual tax deduction for the wear and aging of the property\'s improvements." },
          { name: "Cost Approach Value", desc: "Property value estimated by adding land value to the depreciated cost of improvements." }
        ]
      },
      {
        name: "Highest & Best Use",
        children: [
          { name: "Legally Permissible Uses", desc: "Property uses allowed under current zoning and legal regulations." },
          { name: "Physically Possible Uses", desc: "Uses that the property's physical characteristics can support." },
          { name: "Financially Feasible Uses", desc: "Potential uses that would generate a positive return on investment." },
          { name: "Maximally Productive Use", desc: "The highest and best use that produces the greatest property value." }
        ]
      },
      {
        name: "Market Conditions",
        children: [
          { name: "Cap Rate Trend (Expanding/Compressing)", desc: "Net Operating Income divided by property value, expressing the property\'s yield." },
          { name: "Absorption Rate", desc: "The rate at which finished lots or units are expected to sell per month or quarter." },
          { name: "Days on Market", desc: "The average number of days listed properties take to sell in the current market." },
          { name: "Supply Pipeline", desc: "The number of new properties under construction or planned in the market." },
          { name: "Reconciled Final Value Estimate", desc: "The appraiser's final value opinion after weighing all three approaches." }
        ]
      }
    ]
  }
};

// 25. Subject-To Calculator;
